"""
Pipeline Orchestrator
======================
Cloud-Native Policy Rule Impact Simulation & Audit Governance System

Single execution entry point for the entire governance pipeline.
Designed to be called by the Streamlit UI or any external consumer
with a single function call.

Execution order (strict):
    RULE → SIMULATION → IMPACT → COMPLIANCE → DECISION → AUDIT

Public API:
    run_pipeline(threshold, multiplier) → dict
    invalidate_cache()                  → None   (force dataset reload)
    get_cache_status()                  → dict   (observability hook)
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any

import pandas as pd

from simulation import simulate
from analysis   import analyze
from compliance import check_compliance
from decision   import make_decision
from audit      import log_audit

# ── Constants ─────────────────────────────────────────────────────────────────
DATASET_PATH: str = "data/dataset.csv"

_REQUIRED_COLUMNS: set[str] = {
    "policy_id", "customer_age", "vehicle_age",
    "annual_mileage", "base_rate", "current_premium",
    "risk_segment", "age_group",
}

# ── Module-level dataset cache (load once, reuse across calls) ─────────────────
_df_cache:        pd.DataFrame | None = None
_cache_loaded_at: str | None          = None
_cache_row_count: int | None          = None


# ── Dataset loading ────────────────────────────────────────────────────────────
def _load_dataset() -> pd.DataFrame:
    """
    Load the policy dataset from disk.
    Validates existence, readability, and required column presence.

    Raises
    ------
    FileNotFoundError : If dataset file is missing.
    ValueError        : If dataset is empty or missing required columns.
    """
    if not os.path.exists(DATASET_PATH):
        raise FileNotFoundError(
            "Dataset not found. Ensure data/dataset.csv exists. "
            "Run generate_insurance_data.py first."
        )

    df = pd.read_csv(DATASET_PATH)

    if df.empty:
        raise ValueError(
            f"Dataset at '{DATASET_PATH}' is empty. "
            "Regenerate it using generate_insurance_data.py."
        )

    missing_cols = _REQUIRED_COLUMNS - set(df.columns)
    if missing_cols:
        raise ValueError(
            f"Dataset is missing required columns: {sorted(missing_cols)}. "
            "Ensure the dataset was generated by generate_insurance_data.py."
        )

    return df


def _get_dataset() -> pd.DataFrame:
    """
    Return the cached dataset, loading from disk on the first call.
    Thread-safe for single-process Streamlit deployments.
    """
    global _df_cache, _cache_loaded_at, _cache_row_count

    if _df_cache is None:
        _df_cache        = _load_dataset()
        _cache_loaded_at = datetime.now(timezone.utc).isoformat()
        _cache_row_count = len(_df_cache)

    return _df_cache


# ── Public cache utilities ─────────────────────────────────────────────────────
def invalidate_cache() -> None:
    """
    Force the next run_pipeline() call to reload the dataset from disk.
    Useful when the underlying CSV is regenerated mid-session.
    """
    global _df_cache, _cache_loaded_at, _cache_row_count
    _df_cache        = None
    _cache_loaded_at = None
    _cache_row_count = None


def get_cache_status() -> dict[str, Any]:
    """
    Return observability metadata about the dataset cache.
    Useful for Streamlit sidebar diagnostics or health-check endpoints.
    """
    return {
        "loaded":     _df_cache is not None,
        "loaded_at":  _cache_loaded_at,
        "row_count":  _cache_row_count,
        "source":     DATASET_PATH,
    }


# ── Input validation ───────────────────────────────────────────────────────────
def _validate_rule_inputs(threshold: int | float, multiplier: float) -> None:
    """
    Validate pipeline inputs before touching the dataset.
    Provides human-readable errors for UI callers.
    """
    if not isinstance(threshold, (int, float)) or not (0 < threshold <= 120):
        raise ValueError(
            f"threshold must be a number in (0, 120]; got {threshold!r}."
        )

    if not isinstance(multiplier, (int, float)) or multiplier <= 0:
        raise ValueError(
            f"multiplier must be a positive number; got {multiplier!r}."
        )

    if not (1.0 <= multiplier <= 10.0):
        raise ValueError(
            f"multiplier {multiplier} is outside the acceptable range [1.0, 10.0]. "
            "Use simulation.simulate(..., override_guard=True) for stress testing."
        )


# ── Main pipeline ──────────────────────────────────────────────────────────────
def run_pipeline(threshold: int | float, multiplier: float) -> dict[str, Any]:
    """
    Execute the full governance pipeline for a given pricing rule configuration.

    Orchestrates the complete decision lifecycle in strict order:
        1. Load dataset (cached after first call)
        2. Simulate premium re-pricing across full portfolio
        3. Compute portfolio-level and segment-level impact metrics
        4. Run regulatory compliance validation
        5. Produce final governance decision (APPROVE / REJECT)
        6. Append immutable audit record to data/audit_log.csv

    Parameters
    ----------
    threshold  : Age boundary. Policies where customer_age < threshold
                 receive the risk multiplier; all others receive 1.20.
                 Must be a number in the range (0, 120].
    multiplier : Pricing multiplier applied to base_rate for triggered policies.
                 Must be in [1.0, 10.0].

    Returns
    -------
    dict with keys:
        simulation  - pd.DataFrame : Full portfolio with new_premium, premium_delta
        analysis    - dict         : Portfolio + segment impact metrics
        compliance  - dict         : Violation counts, rates, segment breakdown
        decision    - dict         : APPROVE/REJECT, reason, audit timestamp

    Raises
    ------
    FileNotFoundError : Dataset file missing from data/dataset.csv.
    ValueError        : Invalid threshold or multiplier values.
    RuntimeError      : Any unexpected failure during pipeline execution.
                        Message format: "Pipeline execution failed: <detail>"
    """
    # ── Phase 0: Input validation (before any I/O) ───────────────────────────
    _validate_rule_inputs(threshold, multiplier)

    try:
        # ── Phase 1: Dataset load (cached) ───────────────────────────────────
        df_raw = _get_dataset()

        # ── Phase 2: Simulation ───────────────────────────────────────────────
        df_sim = simulate(df_raw, threshold=threshold, multiplier=multiplier)

        # ── Phase 3: Impact analysis ──────────────────────────────────────────
        analysis_result = analyze(df_sim)

        # ── Phase 4: Compliance validation ───────────────────────────────────
        compliance_result = check_compliance(df_sim)

        # ── Phase 5: Governance decision ──────────────────────────────────────
        decision_result = make_decision(analysis_result, compliance_result)

        # ── Phase 6: Audit logging ────────────────────────────────────────────
        rule_config = {"threshold": threshold, "multiplier": multiplier}
        log_audit(rule_config, decision_result, compliance_result)

    except (FileNotFoundError, ValueError):
        # Re-raise domain errors with their original message intact
        raise

    except Exception as exc:
        raise RuntimeError(f"Pipeline execution failed: {exc}") from exc

    # ── Return structured result (original df_raw never exposed) ─────────────
    return {
        "simulation":  df_sim,
        "analysis":    analysis_result,
        "compliance":  compliance_result,
        "decision":    decision_result,
    }